# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ceb7efbfe5c73fb9a2fb154b0862acdabe2bdd4714d718adc97abdd296759e8f5e61c7f5577f9a3cea3cbf1591b555d1b672b6efc17829bb71957899ec028e8

test:
  secret_key_base: b20a80228bd4df6ebb74a82faf194d589613d520ea3c428a0bed8778ed49112ef9a5d9c75ba43dbc7f9aa57c9824c9956bac37cb6cf286f0d03c6a94eed2f5f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
